import i18n from '../i18n'

// قايمة الدول: كود ISO2 + الاسم بالعربي + كود الاتصال الدولي (من غير +)
// مستخدمة في قايمة اختيار الدولة (بديل عن مربع نص حر) وفي اكتشاف دولة العميل تلقائي من رقم واتساب
export const COUNTRIES = [
  { code: 'AF', name: i18n.t('countries.AF'), dial: '93' },
  { code: 'AL', name: i18n.t('countries.AL'), dial: '355' },
  { code: 'DZ', name: i18n.t('countries.DZ'), dial: '213' },
  { code: 'AD', name: i18n.t('countries.AD'), dial: '376' },
  { code: 'AO', name: i18n.t('countries.AO'), dial: '244' },
  { code: 'AG', name: i18n.t('countries.AG'), dial: '1268' },
  { code: 'AR', name: i18n.t('countries.AR'), dial: '54' },
  { code: 'AM', name: i18n.t('countries.AM'), dial: '374' },
  { code: 'AU', name: i18n.t('countries.AU'), dial: '61' },
  { code: 'AT', name: i18n.t('countries.AT'), dial: '43' },
  { code: 'AZ', name: i18n.t('countries.AZ'), dial: '994' },
  { code: 'BS', name: i18n.t('countries.BS'), dial: '1242' },
  { code: 'BH', name: i18n.t('countries.BH'), dial: '973' },
  { code: 'BD', name: i18n.t('countries.BD'), dial: '880' },
  { code: 'BB', name: i18n.t('countries.BB'), dial: '1246' },
  { code: 'BY', name: i18n.t('countries.BY'), dial: '375' },
  { code: 'BE', name: i18n.t('countries.BE'), dial: '32' },
  { code: 'BZ', name: i18n.t('countries.BZ'), dial: '501' },
  { code: 'BJ', name: i18n.t('countries.BJ'), dial: '229' },
  { code: 'BT', name: i18n.t('countries.BT'), dial: '975' },
  { code: 'BO', name: i18n.t('countries.BO'), dial: '591' },
  { code: 'BA', name: i18n.t('countries.BA'), dial: '387' },
  { code: 'BW', name: i18n.t('countries.BW'), dial: '267' },
  { code: 'BR', name: i18n.t('countries.BR'), dial: '55' },
  { code: 'BN', name: i18n.t('countries.BN'), dial: '673' },
  { code: 'BG', name: i18n.t('countries.BG'), dial: '359' },
  { code: 'BF', name: i18n.t('countries.BF'), dial: '226' },
  { code: 'BI', name: i18n.t('countries.BI'), dial: '257' },
  { code: 'KH', name: i18n.t('countries.KH'), dial: '855' },
  { code: 'CM', name: i18n.t('countries.CM'), dial: '237' },
  { code: 'CA', name: i18n.t('countries.CA'), dial: '1' },
  { code: 'CV', name: i18n.t('countries.CV'), dial: '238' },
  { code: 'CF', name: i18n.t('countries.CF'), dial: '236' },
  { code: 'TD', name: i18n.t('countries.TD'), dial: '235' },
  { code: 'CL', name: i18n.t('countries.CL'), dial: '56' },
  { code: 'CN', name: i18n.t('countries.CN'), dial: '86' },
  { code: 'CO', name: i18n.t('countries.CO'), dial: '57' },
  { code: 'KM', name: i18n.t('countries.KM'), dial: '269' },
  { code: 'CG', name: i18n.t('countries.CG'), dial: '242' },
  { code: 'CD', name: i18n.t('countries.CD'), dial: '243' },
  { code: 'CR', name: i18n.t('countries.CR'), dial: '506' },
  { code: 'CI', name: i18n.t('countries.CI'), dial: '225' },
  { code: 'HR', name: i18n.t('countries.HR'), dial: '385' },
  { code: 'CU', name: i18n.t('countries.CU'), dial: '53' },
  { code: 'CY', name: i18n.t('countries.CY'), dial: '357' },
  { code: 'CZ', name: i18n.t('countries.CZ'), dial: '420' },
  { code: 'DK', name: i18n.t('countries.DK'), dial: '45' },
  { code: 'DJ', name: i18n.t('countries.DJ'), dial: '253' },
  { code: 'DM', name: i18n.t('countries.DM'), dial: '1767' },
  { code: 'DO', name: i18n.t('countries.DO'), dial: '1809' },
  { code: 'EC', name: i18n.t('countries.EC'), dial: '593' },
  { code: 'EG', name: i18n.t('countries.EG'), dial: '20' },
  { code: 'SV', name: i18n.t('countries.SV'), dial: '503' },
  { code: 'GQ', name: i18n.t('countries.GQ'), dial: '240' },
  { code: 'ER', name: i18n.t('countries.ER'), dial: '291' },
  { code: 'EE', name: i18n.t('countries.EE'), dial: '372' },
  { code: 'SZ', name: i18n.t('countries.SZ'), dial: '268' },
  { code: 'ET', name: i18n.t('countries.ET'), dial: '251' },
  { code: 'FJ', name: i18n.t('countries.FJ'), dial: '679' },
  { code: 'FI', name: i18n.t('countries.FI'), dial: '358' },
  { code: 'FR', name: i18n.t('countries.FR'), dial: '33' },
  { code: 'GA', name: i18n.t('countries.GA'), dial: '241' },
  { code: 'GM', name: i18n.t('countries.GM'), dial: '220' },
  { code: 'GE', name: i18n.t('countries.GE'), dial: '995' },
  { code: 'DE', name: i18n.t('countries.DE'), dial: '49' },
  { code: 'GH', name: i18n.t('countries.GH'), dial: '233' },
  { code: 'GR', name: i18n.t('countries.GR'), dial: '30' },
  { code: 'GD', name: i18n.t('countries.GD'), dial: '1473' },
  { code: 'GT', name: i18n.t('countries.GT'), dial: '502' },
  { code: 'GN', name: i18n.t('countries.GN'), dial: '224' },
  { code: 'GW', name: i18n.t('countries.GW'), dial: '245' },
  { code: 'GY', name: i18n.t('countries.GY'), dial: '592' },
  { code: 'HT', name: i18n.t('countries.HT'), dial: '509' },
  { code: 'HN', name: i18n.t('countries.HN'), dial: '504' },
  { code: 'HK', name: i18n.t('countries.HK'), dial: '852' },
  { code: 'HU', name: i18n.t('countries.HU'), dial: '36' },
  { code: 'IS', name: i18n.t('countries.IS'), dial: '354' },
  { code: 'IN', name: i18n.t('countries.IN'), dial: '91' },
  { code: 'ID', name: i18n.t('countries.ID'), dial: '62' },
  { code: 'IR', name: i18n.t('countries.IR'), dial: '98' },
  { code: 'IQ', name: i18n.t('countries.IQ'), dial: '964' },
  { code: 'IE', name: i18n.t('countries.IE'), dial: '353' },
  { code: 'IL', name: i18n.t('countries.IL'), dial: '972' },
  { code: 'IT', name: i18n.t('countries.IT'), dial: '39' },
  { code: 'JM', name: i18n.t('countries.JM'), dial: '1876' },
  { code: 'JP', name: i18n.t('countries.JP'), dial: '81' },
  { code: 'JO', name: i18n.t('countries.JO'), dial: '962' },
  { code: 'KZ', name: i18n.t('countries.KZ'), dial: '7' },
  { code: 'KE', name: i18n.t('countries.KE'), dial: '254' },
  { code: 'KI', name: i18n.t('countries.KI'), dial: '686' },
  { code: 'KW', name: i18n.t('countries.KW'), dial: '965' },
  { code: 'KG', name: i18n.t('countries.KG'), dial: '996' },
  { code: 'LA', name: i18n.t('countries.LA'), dial: '856' },
  { code: 'LV', name: i18n.t('countries.LV'), dial: '371' },
  { code: 'LB', name: i18n.t('countries.LB'), dial: '961' },
  { code: 'LS', name: i18n.t('countries.LS'), dial: '266' },
  { code: 'LR', name: i18n.t('countries.LR'), dial: '231' },
  { code: 'LY', name: i18n.t('countries.LY'), dial: '218' },
  { code: 'LI', name: i18n.t('countries.LI'), dial: '423' },
  { code: 'LT', name: i18n.t('countries.LT'), dial: '370' },
  { code: 'LU', name: i18n.t('countries.LU'), dial: '352' },
  { code: 'MO', name: i18n.t('countries.MO'), dial: '853' },
  { code: 'MG', name: i18n.t('countries.MG'), dial: '261' },
  { code: 'MW', name: i18n.t('countries.MW'), dial: '265' },
  { code: 'MY', name: i18n.t('countries.MY'), dial: '60' },
  { code: 'MV', name: i18n.t('countries.MV'), dial: '960' },
  { code: 'ML', name: i18n.t('countries.ML'), dial: '223' },
  { code: 'MT', name: i18n.t('countries.MT'), dial: '356' },
  { code: 'MR', name: i18n.t('countries.MR'), dial: '222' },
  { code: 'MU', name: i18n.t('countries.MU'), dial: '230' },
  { code: 'MX', name: i18n.t('countries.MX'), dial: '52' },
  { code: 'MD', name: i18n.t('countries.MD'), dial: '373' },
  { code: 'MC', name: i18n.t('countries.MC'), dial: '377' },
  { code: 'MN', name: i18n.t('countries.MN'), dial: '976' },
  { code: 'ME', name: i18n.t('countries.ME'), dial: '382' },
  { code: 'MA', name: i18n.t('countries.MA'), dial: '212' },
  { code: 'MZ', name: i18n.t('countries.MZ'), dial: '258' },
  { code: 'MM', name: i18n.t('countries.MM'), dial: '95' },
  { code: 'NA', name: i18n.t('countries.NA'), dial: '264' },
  { code: 'NP', name: i18n.t('countries.NP'), dial: '977' },
  { code: 'NL', name: i18n.t('countries.NL'), dial: '31' },
  { code: 'NZ', name: i18n.t('countries.NZ'), dial: '64' },
  { code: 'NI', name: i18n.t('countries.NI'), dial: '505' },
  { code: 'NE', name: i18n.t('countries.NE'), dial: '227' },
  { code: 'NG', name: i18n.t('countries.NG'), dial: '234' },
  { code: 'KP', name: i18n.t('countries.KP'), dial: '850' },
  { code: 'MK', name: i18n.t('countries.MK'), dial: '389' },
  { code: 'NO', name: i18n.t('countries.NO'), dial: '47' },
  { code: 'OM', name: i18n.t('countries.OM'), dial: '968' },
  { code: 'PK', name: i18n.t('countries.PK'), dial: '92' },
  { code: 'PA', name: i18n.t('countries.PA'), dial: '507' },
  { code: 'PG', name: i18n.t('countries.PG'), dial: '675' },
  { code: 'PY', name: i18n.t('countries.PY'), dial: '595' },
  { code: 'PE', name: i18n.t('countries.PE'), dial: '51' },
  { code: 'PH', name: i18n.t('countries.PH'), dial: '63' },
  { code: 'PL', name: i18n.t('countries.PL'), dial: '48' },
  { code: 'PT', name: i18n.t('countries.PT'), dial: '351' },
  { code: 'QA', name: i18n.t('countries.QA'), dial: '974' },
  { code: 'RO', name: i18n.t('countries.RO'), dial: '40' },
  { code: 'RU', name: i18n.t('countries.RU'), dial: '7' },
  { code: 'RW', name: i18n.t('countries.RW'), dial: '250' },
  { code: 'KN', name: i18n.t('countries.KN'), dial: '1869' },
  { code: 'LC', name: i18n.t('countries.LC'), dial: '1758' },
  { code: 'VC', name: i18n.t('countries.VC'), dial: '1784' },
  { code: 'WS', name: i18n.t('countries.WS'), dial: '685' },
  { code: 'SM', name: i18n.t('countries.SM'), dial: '378' },
  { code: 'ST', name: i18n.t('countries.ST'), dial: '239' },
  { code: 'SA', name: i18n.t('countries.SA'), dial: '966' },
  { code: 'SN', name: i18n.t('countries.SN'), dial: '221' },
  { code: 'RS', name: i18n.t('countries.RS'), dial: '381' },
  { code: 'SC', name: i18n.t('countries.SC'), dial: '248' },
  { code: 'SL', name: i18n.t('countries.SL'), dial: '232' },
  { code: 'SG', name: i18n.t('countries.SG'), dial: '65' },
  { code: 'SK', name: i18n.t('countries.SK'), dial: '421' },
  { code: 'SI', name: i18n.t('countries.SI'), dial: '386' },
  { code: 'SB', name: i18n.t('countries.SB'), dial: '677' },
  { code: 'SO', name: i18n.t('countries.SO'), dial: '252' },
  { code: 'ZA', name: i18n.t('countries.ZA'), dial: '27' },
  { code: 'KR', name: i18n.t('countries.KR'), dial: '82' },
  { code: 'SS', name: i18n.t('countries.SS'), dial: '211' },
  { code: 'ES', name: i18n.t('countries.ES'), dial: '34' },
  { code: 'LK', name: i18n.t('countries.LK'), dial: '94' },
  { code: 'SD', name: i18n.t('countries.SD'), dial: '249' },
  { code: 'SR', name: i18n.t('countries.SR'), dial: '597' },
  { code: 'SE', name: i18n.t('countries.SE'), dial: '46' },
  { code: 'CH', name: i18n.t('countries.CH'), dial: '41' },
  { code: 'SY', name: i18n.t('countries.SY'), dial: '963' },
  { code: 'TW', name: i18n.t('countries.TW'), dial: '886' },
  { code: 'TJ', name: i18n.t('countries.TJ'), dial: '992' },
  { code: 'TZ', name: i18n.t('countries.TZ'), dial: '255' },
  { code: 'TH', name: i18n.t('countries.TH'), dial: '66' },
  { code: 'TL', name: i18n.t('countries.TL'), dial: '670' },
  { code: 'TG', name: i18n.t('countries.TG'), dial: '228' },
  { code: 'TO', name: i18n.t('countries.TO'), dial: '676' },
  { code: 'TT', name: i18n.t('countries.TT'), dial: '1868' },
  { code: 'TN', name: i18n.t('countries.TN'), dial: '216' },
  { code: 'TR', name: i18n.t('countries.TR'), dial: '90' },
  { code: 'TM', name: i18n.t('countries.TM'), dial: '993' },
  { code: 'TV', name: i18n.t('countries.TV'), dial: '688' },
  { code: 'UG', name: i18n.t('countries.UG'), dial: '256' },
  { code: 'UA', name: i18n.t('countries.UA'), dial: '380' },
  { code: 'AE', name: i18n.t('countries.AE'), dial: '971' },
  { code: 'GB', name: i18n.t('countries.GB'), dial: '44' },
  { code: 'US', name: i18n.t('countries.US'), dial: '1' },
  { code: 'UY', name: i18n.t('countries.UY'), dial: '598' },
  { code: 'UZ', name: i18n.t('countries.UZ'), dial: '998' },
  { code: 'VU', name: i18n.t('countries.VU'), dial: '678' },
  { code: 'VA', name: i18n.t('countries.VA'), dial: '379' },
  { code: 'VE', name: i18n.t('countries.VE'), dial: '58' },
  { code: 'VN', name: i18n.t('countries.VN'), dial: '84' },
  { code: 'YE', name: i18n.t('countries.YE'), dial: '967' },
  { code: 'ZM', name: i18n.t('countries.ZM'), dial: '260' },
  { code: 'ZW', name: i18n.t('countries.ZW'), dial: '263' },
  { code: 'PS', name: i18n.t('countries.PS'), dial: '970' },
]

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.code, c]))

// أرقام كود ١ (NANP) بتتشارك بين أمريكا وكندا ودول الكاريبي — أكواد المنطقة (أول ٣ أرقام بعد
// الـ 1) هي اللي بتفرّق. القايمة دي بتغطي أكواد كندا المعروفة؛ أي كود تاني مش فيها بنفترضه أمريكا
const CANADA_AREA_CODES = new Set([
  '204', '226', '236', '249', '250', '289', '306', '343', '365', '367',
  '403', '416', '418', '431', '437', '438', '450', '506', '514', '519',
  '548', '579', '581', '587', '604', '613', '639', '647', '672', '705',
  '709', '778', '780', '782', '807', '819', '825', '867', '873', '902', '905',
])

// بيدور على الدولة الأقرب لرقم تليفون دولي (من غير +)، بمطابقة أطول كود اتصال ممكن
// (مثلاً +1 ممكن تبقى أمريكا أو كندا أو غيرها، فبنستخدم كود المنطقة عشان نفرّق بينهم)
export function detectCountryFromPhone(phone) {
  if (!phone) return null
  const digits = String(phone).replace(/\D/g, '')
  if (!digits) return null

  if (digits.startsWith('1') && digits.length >= 4) {
    const areaCode = digits.slice(1, 4)
    return CANADA_AREA_CODES.has(areaCode) ? 'CA' : 'US'
  }

  // أطول كود اتصال متطابق الأول (عشان أكواد زي 20 و20xxx متتلخبطش)
  const sorted = [...COUNTRIES].sort((a, b) => b.dial.length - a.dial.length)
  const match = sorted.find(c => digits.startsWith(c.dial))
  return match?.code || null
}
