// قايمة الدول: كود ISO2 + الاسم بالعربي + كود الاتصال الدولي (من غير +)
// مستخدمة في قايمة اختيار الدولة (بديل عن مربع نص حر) وفي اكتشاف دولة العميل تلقائي من رقم واتساب
export const COUNTRIES = [
  { code: 'AF', name: 'أفغانستان', dial: '93' },
  { code: 'AL', name: 'ألبانيا', dial: '355' },
  { code: 'DZ', name: 'الجزائر', dial: '213' },
  { code: 'AD', name: 'أندورا', dial: '376' },
  { code: 'AO', name: 'أنجولا', dial: '244' },
  { code: 'AG', name: 'أنتيجوا وباربودا', dial: '1268' },
  { code: 'AR', name: 'الأرجنتين', dial: '54' },
  { code: 'AM', name: 'أرمينيا', dial: '374' },
  { code: 'AU', name: 'أستراليا', dial: '61' },
  { code: 'AT', name: 'النمسا', dial: '43' },
  { code: 'AZ', name: 'أذربيجان', dial: '994' },
  { code: 'BS', name: 'باهاماس', dial: '1242' },
  { code: 'BH', name: 'البحرين', dial: '973' },
  { code: 'BD', name: 'بنجلاديش', dial: '880' },
  { code: 'BB', name: 'باربادوس', dial: '1246' },
  { code: 'BY', name: 'بيلاروسيا', dial: '375' },
  { code: 'BE', name: 'بلجيكا', dial: '32' },
  { code: 'BZ', name: 'بليز', dial: '501' },
  { code: 'BJ', name: 'بنين', dial: '229' },
  { code: 'BT', name: 'بوتان', dial: '975' },
  { code: 'BO', name: 'بوليفيا', dial: '591' },
  { code: 'BA', name: 'البوسنة والهرسك', dial: '387' },
  { code: 'BW', name: 'بوتسوانا', dial: '267' },
  { code: 'BR', name: 'البرازيل', dial: '55' },
  { code: 'BN', name: 'بروناي', dial: '673' },
  { code: 'BG', name: 'بلغاريا', dial: '359' },
  { code: 'BF', name: 'بوركينا فاسو', dial: '226' },
  { code: 'BI', name: 'بوروندي', dial: '257' },
  { code: 'KH', name: 'كمبوديا', dial: '855' },
  { code: 'CM', name: 'الكاميرون', dial: '237' },
  { code: 'CA', name: 'كندا', dial: '1' },
  { code: 'CV', name: 'الرأس الأخضر', dial: '238' },
  { code: 'CF', name: 'جمهورية أفريقيا الوسطى', dial: '236' },
  { code: 'TD', name: 'تشاد', dial: '235' },
  { code: 'CL', name: 'تشيلي', dial: '56' },
  { code: 'CN', name: 'الصين', dial: '86' },
  { code: 'CO', name: 'كولومبيا', dial: '57' },
  { code: 'KM', name: 'جزر القمر', dial: '269' },
  { code: 'CG', name: 'الكونغو', dial: '242' },
  { code: 'CD', name: 'الكونغو الديمقراطية', dial: '243' },
  { code: 'CR', name: 'كوستاريكا', dial: '506' },
  { code: 'CI', name: 'ساحل العاج', dial: '225' },
  { code: 'HR', name: 'كرواتيا', dial: '385' },
  { code: 'CU', name: 'كوبا', dial: '53' },
  { code: 'CY', name: 'قبرص', dial: '357' },
  { code: 'CZ', name: 'التشيك', dial: '420' },
  { code: 'DK', name: 'الدنمارك', dial: '45' },
  { code: 'DJ', name: 'جيبوتي', dial: '253' },
  { code: 'DM', name: 'دومينيكا', dial: '1767' },
  { code: 'DO', name: 'جمهورية الدومينيكان', dial: '1809' },
  { code: 'EC', name: 'الإكوادور', dial: '593' },
  { code: 'EG', name: 'مصر', dial: '20' },
  { code: 'SV', name: 'السلفادور', dial: '503' },
  { code: 'GQ', name: 'غينيا الاستوائية', dial: '240' },
  { code: 'ER', name: 'إريتريا', dial: '291' },
  { code: 'EE', name: 'إستونيا', dial: '372' },
  { code: 'SZ', name: 'إسواتيني', dial: '268' },
  { code: 'ET', name: 'إثيوبيا', dial: '251' },
  { code: 'FJ', name: 'فيجي', dial: '679' },
  { code: 'FI', name: 'فنلندا', dial: '358' },
  { code: 'FR', name: 'فرنسا', dial: '33' },
  { code: 'GA', name: 'الجابون', dial: '241' },
  { code: 'GM', name: 'غامبيا', dial: '220' },
  { code: 'GE', name: 'جورجيا', dial: '995' },
  { code: 'DE', name: 'ألمانيا', dial: '49' },
  { code: 'GH', name: 'غانا', dial: '233' },
  { code: 'GR', name: 'اليونان', dial: '30' },
  { code: 'GD', name: 'جرينادا', dial: '1473' },
  { code: 'GT', name: 'جواتيمالا', dial: '502' },
  { code: 'GN', name: 'غينيا', dial: '224' },
  { code: 'GW', name: 'غينيا بيساو', dial: '245' },
  { code: 'GY', name: 'غيانا', dial: '592' },
  { code: 'HT', name: 'هايتي', dial: '509' },
  { code: 'HN', name: 'هندوراس', dial: '504' },
  { code: 'HK', name: 'هونج كونج', dial: '852' },
  { code: 'HU', name: 'المجر', dial: '36' },
  { code: 'IS', name: 'آيسلندا', dial: '354' },
  { code: 'IN', name: 'الهند', dial: '91' },
  { code: 'ID', name: 'إندونيسيا', dial: '62' },
  { code: 'IR', name: 'إيران', dial: '98' },
  { code: 'IQ', name: 'العراق', dial: '964' },
  { code: 'IE', name: 'أيرلندا', dial: '353' },
  { code: 'IL', name: 'إسرائيل', dial: '972' },
  { code: 'IT', name: 'إيطاليا', dial: '39' },
  { code: 'JM', name: 'جامايكا', dial: '1876' },
  { code: 'JP', name: 'اليابان', dial: '81' },
  { code: 'JO', name: 'الأردن', dial: '962' },
  { code: 'KZ', name: 'كازاخستان', dial: '7' },
  { code: 'KE', name: 'كينيا', dial: '254' },
  { code: 'KI', name: 'كيريباتي', dial: '686' },
  { code: 'KW', name: 'الكويت', dial: '965' },
  { code: 'KG', name: 'قيرغيزستان', dial: '996' },
  { code: 'LA', name: 'لاوس', dial: '856' },
  { code: 'LV', name: 'لاتفيا', dial: '371' },
  { code: 'LB', name: 'لبنان', dial: '961' },
  { code: 'LS', name: 'ليسوتو', dial: '266' },
  { code: 'LR', name: 'ليبيريا', dial: '231' },
  { code: 'LY', name: 'ليبيا', dial: '218' },
  { code: 'LI', name: 'ليختنشتاين', dial: '423' },
  { code: 'LT', name: 'ليتوانيا', dial: '370' },
  { code: 'LU', name: 'لوكسمبورج', dial: '352' },
  { code: 'MO', name: 'ماكاو', dial: '853' },
  { code: 'MG', name: 'مدغشقر', dial: '261' },
  { code: 'MW', name: 'مالاوي', dial: '265' },
  { code: 'MY', name: 'ماليزيا', dial: '60' },
  { code: 'MV', name: 'المالديف', dial: '960' },
  { code: 'ML', name: 'مالي', dial: '223' },
  { code: 'MT', name: 'مالطا', dial: '356' },
  { code: 'MR', name: 'موريتانيا', dial: '222' },
  { code: 'MU', name: 'موريشيوس', dial: '230' },
  { code: 'MX', name: 'المكسيك', dial: '52' },
  { code: 'MD', name: 'مولدوفا', dial: '373' },
  { code: 'MC', name: 'موناكو', dial: '377' },
  { code: 'MN', name: 'منغوليا', dial: '976' },
  { code: 'ME', name: 'الجبل الأسود', dial: '382' },
  { code: 'MA', name: 'المغرب', dial: '212' },
  { code: 'MZ', name: 'موزمبيق', dial: '258' },
  { code: 'MM', name: 'ميانمار', dial: '95' },
  { code: 'NA', name: 'ناميبيا', dial: '264' },
  { code: 'NP', name: 'نيبال', dial: '977' },
  { code: 'NL', name: 'هولندا', dial: '31' },
  { code: 'NZ', name: 'نيوزيلندا', dial: '64' },
  { code: 'NI', name: 'نيكاراجوا', dial: '505' },
  { code: 'NE', name: 'النيجر', dial: '227' },
  { code: 'NG', name: 'نيجيريا', dial: '234' },
  { code: 'KP', name: 'كوريا الشمالية', dial: '850' },
  { code: 'MK', name: 'مقدونيا الشمالية', dial: '389' },
  { code: 'NO', name: 'النرويج', dial: '47' },
  { code: 'OM', name: 'عُمان', dial: '968' },
  { code: 'PK', name: 'باكستان', dial: '92' },
  { code: 'PA', name: 'بنما', dial: '507' },
  { code: 'PG', name: 'بابوا غينيا الجديدة', dial: '675' },
  { code: 'PY', name: 'باراجواي', dial: '595' },
  { code: 'PE', name: 'بيرو', dial: '51' },
  { code: 'PH', name: 'الفلبين', dial: '63' },
  { code: 'PL', name: 'بولندا', dial: '48' },
  { code: 'PT', name: 'البرتغال', dial: '351' },
  { code: 'QA', name: 'قطر', dial: '974' },
  { code: 'RO', name: 'رومانيا', dial: '40' },
  { code: 'RU', name: 'روسيا', dial: '7' },
  { code: 'RW', name: 'رواندا', dial: '250' },
  { code: 'KN', name: 'سانت كيتس ونيفيس', dial: '1869' },
  { code: 'LC', name: 'سانت لوسيا', dial: '1758' },
  { code: 'VC', name: 'سانت فينسنت والغرينادين', dial: '1784' },
  { code: 'WS', name: 'ساموا', dial: '685' },
  { code: 'SM', name: 'سان مارينو', dial: '378' },
  { code: 'ST', name: 'ساو تومي وبرينسيب', dial: '239' },
  { code: 'SA', name: 'السعودية', dial: '966' },
  { code: 'SN', name: 'السنغال', dial: '221' },
  { code: 'RS', name: 'صربيا', dial: '381' },
  { code: 'SC', name: 'سيشل', dial: '248' },
  { code: 'SL', name: 'سيراليون', dial: '232' },
  { code: 'SG', name: 'سنغافورة', dial: '65' },
  { code: 'SK', name: 'سلوفاكيا', dial: '421' },
  { code: 'SI', name: 'سلوفينيا', dial: '386' },
  { code: 'SB', name: 'جزر سليمان', dial: '677' },
  { code: 'SO', name: 'الصومال', dial: '252' },
  { code: 'ZA', name: 'جنوب أفريقيا', dial: '27' },
  { code: 'KR', name: 'كوريا الجنوبية', dial: '82' },
  { code: 'SS', name: 'جنوب السودان', dial: '211' },
  { code: 'ES', name: 'إسبانيا', dial: '34' },
  { code: 'LK', name: 'سريلانكا', dial: '94' },
  { code: 'SD', name: 'السودان', dial: '249' },
  { code: 'SR', name: 'سورينام', dial: '597' },
  { code: 'SE', name: 'السويد', dial: '46' },
  { code: 'CH', name: 'سويسرا', dial: '41' },
  { code: 'SY', name: 'سوريا', dial: '963' },
  { code: 'TW', name: 'تايوان', dial: '886' },
  { code: 'TJ', name: 'طاجيكستان', dial: '992' },
  { code: 'TZ', name: 'تنزانيا', dial: '255' },
  { code: 'TH', name: 'تايلاند', dial: '66' },
  { code: 'TL', name: 'تيمور الشرقية', dial: '670' },
  { code: 'TG', name: 'توجو', dial: '228' },
  { code: 'TO', name: 'تونجا', dial: '676' },
  { code: 'TT', name: 'ترينيداد وتوباجو', dial: '1868' },
  { code: 'TN', name: 'تونس', dial: '216' },
  { code: 'TR', name: 'تركيا', dial: '90' },
  { code: 'TM', name: 'تركمانستان', dial: '993' },
  { code: 'TV', name: 'توفالو', dial: '688' },
  { code: 'UG', name: 'أوغندا', dial: '256' },
  { code: 'UA', name: 'أوكرانيا', dial: '380' },
  { code: 'AE', name: 'الإمارات', dial: '971' },
  { code: 'GB', name: 'بريطانيا', dial: '44' },
  { code: 'US', name: 'أمريكا', dial: '1' },
  { code: 'UY', name: 'أوروجواي', dial: '598' },
  { code: 'UZ', name: 'أوزبكستان', dial: '998' },
  { code: 'VU', name: 'فانواتو', dial: '678' },
  { code: 'VA', name: 'الفاتيكان', dial: '379' },
  { code: 'VE', name: 'فنزويلا', dial: '58' },
  { code: 'VN', name: 'فيتنام', dial: '84' },
  { code: 'YE', name: 'اليمن', dial: '967' },
  { code: 'ZM', name: 'زامبيا', dial: '260' },
  { code: 'ZW', name: 'زيمبابوي', dial: '263' },
  { code: 'PS', name: 'فلسطين', dial: '970' },
]

export const COUNTRY_MAP = Object.fromEntries(COUNTRIES.map(c => [c.code, c]))

// أرقام كود ١ (NANP) بتتشارك بين أمريكا وكندا ودول الكاريبي — أكواد المنطقة (أول ٣ أرقام بعد
// الـ 1) هي اللي بتفرّق. القايمة دي بتغطي أكواد كندا المعروفة؛ أي كود تاني مش فيها بنفترضه أمريكا
const CANADA_AREA_CODES = new Set([
  '204', '226', '236', '249', '250', '289', '306', '343', '365', '367',
  '403', '416', '418', '431', '437', '438', '450', '506', '514', '519',
  '548', '579', '581', '587', '604', '613', '639', '647', '672', '705',
  '709', '778', '780', '782', '807', '819', '825', '867', '873', '902', '905',
])

// بيدور على الدولة الأقرب لرقم تليفون دولي (من غير +)، بمطابقة أطول كود اتصال ممكن
// (مثلاً +1 ممكن تبقى أمريكا أو كندا أو غيرها، فبنستخدم كود المنطقة عشان نفرّق بينهم)
export function detectCountryFromPhone(phone) {
  if (!phone) return null
  const digits = String(phone).replace(/\D/g, '')
  if (!digits) return null

  if (digits.startsWith('1') && digits.length >= 4) {
    const areaCode = digits.slice(1, 4)
    return CANADA_AREA_CODES.has(areaCode) ? 'CA' : 'US'
  }

  // أطول كود اتصال متطابق الأول (عشان أكواد زي 20 و20xxx متتلخبطش)
  const sorted = [...COUNTRIES].sort((a, b) => b.dial.length - a.dial.length)
  const match = sorted.find(c => digits.startsWith(c.dial))
  return match?.code || null
}
